-- MySQL Script generated by MySQL Workbench
-- Mon Nov 27 19:46:53 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema smartcupon
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `smartcupon` ;

-- -----------------------------------------------------
-- Schema smartcupon
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `smartcupon` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `smartcupon` ;

-- -----------------------------------------------------
-- Table `smartcupon`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartcupon`.`categoria` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `nombreCategoria` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `smartcupon`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartcupon`.`cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `apellidoPaterno` VARCHAR(100) NULL DEFAULT NULL,
  `apellidoMaterno` VARCHAR(100) NULL DEFAULT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  `correoElectronico` VARCHAR(100) NULL DEFAULT NULL,
  `fechaNacimiento` DATE NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `correoElectronico` ON `smartcupon`.`cliente` (`correoElectronico` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `smartcupon`.`tipo_promocion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartcupon`.`tipo_promocion` (
  `idTipoPromocion` INT NOT NULL AUTO_INCREMENT,
  `nombreTipo` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idTipoPromocion`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `smartcupon`.`estatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartcupon`.`estatus` (
  `idEstatus` INT NOT NULL AUTO_INCREMENT,
  `nombreEstatus` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idEstatus`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `smartcupon`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartcupon`.`empresa` (
  `RFC` VARCHAR(20) NOT NULL,
  `nombre` VARCHAR(255) NOT NULL,
  `nombreComercial` VARCHAR(255) NULL DEFAULT NULL,
  `representanteLegal` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  `paginaWeb` VARCHAR(255) NULL DEFAULT NULL,
  `estatusID` INT NULL DEFAULT '1',
  `logo` LONGBLOB NULL DEFAULT NULL,
  PRIMARY KEY (`RFC`),
  CONSTRAINT `empresa_ibfk_1`
    FOREIGN KEY (`estatusID`)
    REFERENCES `smartcupon`.`estatus` (`idEstatus`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `RFC_UNIQUE` ON `smartcupon`.`empresa` (`RFC` ASC) VISIBLE;

CREATE INDEX `estatusID` ON `smartcupon`.`empresa` (`estatusID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `smartcupon`.`promocion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartcupon`.`promocion` (
  `idPromocion` INT NOT NULL AUTO_INCREMENT,
  `nombrePromocion` VARCHAR(255) NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `fechaInicio` DATE NULL DEFAULT NULL,
  `fechaTermino` DATE NULL DEFAULT NULL,
  `restricciones` TEXT NULL DEFAULT NULL,
  `idTipoPromocion` INT NULL DEFAULT NULL,
  `porcentajeDescuento` DECIMAL(5,2) NULL DEFAULT NULL,
  `codigoPromocion` VARCHAR(8) NULL DEFAULT NULL,
  `idEstatus` INT NULL DEFAULT '1',
  `empresaRFC` VARCHAR(20) NOT NULL,
  `idCategoria` INT NULL DEFAULT NULL,
  `imagen` LONGBLOB NULL DEFAULT NULL,
  PRIMARY KEY (`idPromocion`),
  CONSTRAINT `categoriaID`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `smartcupon`.`categoria` (`idCategoria`),
  CONSTRAINT `promocion_ibfk_1`
    FOREIGN KEY (`idTipoPromocion`)
    REFERENCES `smartcupon`.`tipo_promocion` (`idTipoPromocion`),
  CONSTRAINT `promocion_ibfk_2`
    FOREIGN KEY (`idEstatus`)
    REFERENCES `smartcupon`.`estatus` (`idEstatus`),
  CONSTRAINT `promocion_ibfk_3`
    FOREIGN KEY (`empresaRFC`)
    REFERENCES `smartcupon`.`empresa` (`RFC`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `codigoPromocion` ON `smartcupon`.`promocion` (`codigoPromocion` ASC) VISIBLE;

CREATE INDEX `empresaRFC` ON `smartcupon`.`promocion` (`empresaRFC` ASC) VISIBLE;

CREATE INDEX `promocion_ibfk_1` ON `smartcupon`.`promocion` (`idTipoPromocion` ASC) VISIBLE;

CREATE INDEX `promocion_ibfk_2` ON `smartcupon`.`promocion` (`idEstatus` ASC) VISIBLE;

CREATE INDEX `categoriaID` ON `smartcupon`.`promocion` (`idCategoria` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `smartcupon`.`cupon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartcupon`.`cupon` (
  `idCupon` INT NOT NULL AUTO_INCREMENT,
  `codigoCupon` VARCHAR(8) NOT NULL,
  `idPromocion` INT NOT NULL,
  `fechaGeneracion` DATE NULL DEFAULT NULL,
  `idEstatus` INT NULL DEFAULT NULL,
  `usosDisponibles` INT NOT NULL DEFAULT '1',
  PRIMARY KEY (`idCupon`),
  CONSTRAINT `cupon_ibfk_1`
    FOREIGN KEY (`idPromocion`)
    REFERENCES `smartcupon`.`promocion` (`idPromocion`),
  CONSTRAINT `cupon_ibfk_2`
    FOREIGN KEY (`idEstatus`)
    REFERENCES `smartcupon`.`estatus` (`idEstatus`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `codigoCupon` ON `smartcupon`.`cupon` (`codigoCupon` ASC) VISIBLE;

CREATE INDEX `cupon_ibfk_2` ON `smartcupon`.`cupon` (`idEstatus` ASC) VISIBLE;

CREATE INDEX `cupon_ibfk_1` ON `smartcupon`.`cupon` (`idPromocion` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `smartcupon`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartcupon`.`estado` (
  `idEstado` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEstado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `nombreEstado_UNIQUE` ON `smartcupon`.`estado` (`nombre` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `smartcupon`.`municipio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartcupon`.`municipio` (
  `idMunicipio` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `idEstado` INT NOT NULL,
  PRIMARY KEY (`idMunicipio`),
  CONSTRAINT `idEstado`
    FOREIGN KEY (`idEstado`)
    REFERENCES `smartcupon`.`estado` (`idEstado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `idEstado_idx` ON `smartcupon`.`municipio` (`idEstado` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `smartcupon`.`sucursal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartcupon`.`sucursal` (
  `idSucursal` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  `latitud` DECIMAL(10,8) NULL DEFAULT NULL,
  `longitud` DECIMAL(11,8) NULL DEFAULT NULL,
  `nombreEncargado` VARCHAR(255) NULL DEFAULT NULL,
  `empresaRFC` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idSucursal`),
  CONSTRAINT `sucursal_ibfk_1`
    FOREIGN KEY (`empresaRFC`)
    REFERENCES `smartcupon`.`empresa` (`RFC`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `empresaRFC` ON `smartcupon`.`sucursal` (`empresaRFC` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `smartcupon`.`direccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartcupon`.`direccion` (
  `idDireccion` INT NOT NULL AUTO_INCREMENT,
  `calle` VARCHAR(255) NOT NULL,
  `numero` INT NOT NULL,
  `codigoPostal` VARCHAR(10) NULL DEFAULT NULL,
  `colonia` VARCHAR(100) NULL DEFAULT NULL,
  `idMunicipio` INT NULL DEFAULT NULL,
  `idCliente` INT NULL DEFAULT NULL,
  `empresaRFC` VARCHAR(45) NULL DEFAULT NULL,
  `idSucursal` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idDireccion`),
  CONSTRAINT `empresaRFC`
    FOREIGN KEY (`empresaRFC`)
    REFERENCES `smartcupon`.`empresa` (`RFC`),
  CONSTRAINT `idCliente`
    FOREIGN KEY (`idCliente`)
    REFERENCES `smartcupon`.`cliente` (`idCliente`),
  CONSTRAINT `idMunicipio`
    FOREIGN KEY (`idMunicipio`)
    REFERENCES `smartcupon`.`municipio` (`idMunicipio`),
  CONSTRAINT `idSucursal`
    FOREIGN KEY (`idSucursal`)
    REFERENCES `smartcupon`.`sucursal` (`idSucursal`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `empresaRFC_idx` ON `smartcupon`.`direccion` (`empresaRFC` ASC) VISIBLE;

CREATE INDEX `idCliente_idx` ON `smartcupon`.`direccion` (`idCliente` ASC) VISIBLE;

CREATE INDEX `idSucursal_idx` ON `smartcupon`.`direccion` (`idSucursal` ASC) VISIBLE;

CREATE INDEX `idMunicipio_idx` ON `smartcupon`.`direccion` (`idMunicipio` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `smartcupon`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartcupon`.`rol` (
  `idRol` INT NOT NULL AUTO_INCREMENT,
  `nombreRol` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idRol`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `smartcupon`.`sucursal_promocion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartcupon`.`sucursal_promocion` (
  `idSucursalPromocion` INT NOT NULL AUTO_INCREMENT,
  `sucursalID` INT NULL DEFAULT NULL,
  `promocionID` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idSucursalPromocion`),
  CONSTRAINT `sucursal_promocion_ibfk_1`
    FOREIGN KEY (`sucursalID`)
    REFERENCES `smartcupon`.`sucursal` (`idSucursal`),
  CONSTRAINT `sucursal_promocion_ibfk_2`
    FOREIGN KEY (`promocionID`)
    REFERENCES `smartcupon`.`promocion` (`idPromocion`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `sucursalID` ON `smartcupon`.`sucursal_promocion` (`sucursalID` ASC) VISIBLE;

CREATE INDEX `promocionID` ON `smartcupon`.`sucursal_promocion` (`promocionID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `smartcupon`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartcupon`.`usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `apellidoPaterno` VARCHAR(100) NULL DEFAULT NULL,
  `apellidoMaterno` VARCHAR(100) NULL DEFAULT NULL,
  `CURP` VARCHAR(18) NOT NULL,
  `correoElectronico` VARCHAR(100) NOT NULL,
  `username` VARCHAR(50) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `rolID` INT NOT NULL,
  `empresaRFC` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`idUsuario`),
  CONSTRAINT `usuario_ibfk_1`
    FOREIGN KEY (`rolID`)
    REFERENCES `smartcupon`.`rol` (`idRol`),
  CONSTRAINT `usuario_ibfk_2`
    FOREIGN KEY (`empresaRFC`)
    REFERENCES `smartcupon`.`empresa` (`RFC`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `CURP` ON `smartcupon`.`usuario` (`CURP` ASC) VISIBLE;

CREATE UNIQUE INDEX `correoElectronico` ON `smartcupon`.`usuario` (`correoElectronico` ASC) VISIBLE;

CREATE UNIQUE INDEX `username` ON `smartcupon`.`usuario` (`username` ASC) VISIBLE;

CREATE INDEX `usuario_ibfk_1` ON `smartcupon`.`usuario` (`rolID` ASC) VISIBLE;

CREATE INDEX `usuario_ibfk_2` ON `smartcupon`.`usuario` (`empresaRFC` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



----------------------------------------------

-- Creacion de usuario y asignacion de permisos 
CREATE USER 'Eduard'@'127.0.0.1' IDENTIFIED BY 'FlowLetal';
GRANT ALL PRIVILEGES ON smartcupon TO 'Eduard'@'127.0.0.1';

----------------------------------------------------

-- Crear base de datos si no existe
CREATE DATABASE IF NOT EXISTS smartcupon;
USE smartcupon;

-- Tablas primarias
CREATE TABLE estado (
    id_estado int AUTO_INCREMENT PRIMARY KEY,
    nombre varchar(45)
);

CREATE TABLE estatus (
    id_estatus int AUTO_INCREMENT PRIMARY KEY,
    nombre_estatus varchar(50)
);

CREATE TABLE tipo_promocion (
    id_tipo_promocion int AUTO_INCREMENT PRIMARY KEY,
    nombre_tipo varchar(50)
);

CREATE TABLE categoria (
    id_categoria int AUTO_INCREMENT PRIMARY KEY,
    nombre_categoria varchar(100)
);

CREATE TABLE rol (
    id_rol int AUTO_INCREMENT PRIMARY KEY,
    nombre_rol varchar(50)
);

CREATE TABLE empresa (
    rfc varchar(20) PRIMARY KEY,
    nombre varchar(255),
    nombre_comercial varchar(255),
    representante_legal varchar(255),
    email varchar(100),
    telefono varchar(20),
    pagina_web varchar(255),
    id_estatus int,
    logo longblob,
    FOREIGN KEY (id_estatus) REFERENCES estatus(id_estatus)
);

CREATE TABLE cliente (
    id_cliente int AUTO_INCREMENT PRIMARY KEY,
    nombre varchar(100),
    apellido_paterno varchar(100),
    apellido_materno varchar(100),
    telefono varchar(20),
    correo_electronico varchar(100),
    fecha_nacimiento date,
    password varchar(255)
);

CREATE TABLE usuario (
    id_usuario int AUTO_INCREMENT PRIMARY KEY,
    nombre varchar(100),
    apellido_paterno varchar(100),
    apellido_materno varchar(100),
    curp varchar(18),
    correo_electronico varchar(100),
    username varchar(50),
    password varchar(255),
    id_rol int,
    empresa_rfc varchar(20),
    FOREIGN KEY (id_rol) REFERENCES rol(id_rol),
    FOREIGN KEY (empresa_rfc) REFERENCES empresa(rfc)
);

-- Tablas con referencias a tablas primarias creadas previamente
CREATE TABLE promocion (
    id_promocion int AUTO_INCREMENT PRIMARY KEY,
    nombre_promocion varchar(255),
    descripcion text,
    fecha_inicio date,
    fecha_termino date,
    restricciones text,
    id_tipo_promocion int,
    porcentaje_descuento decimal(5,2),
    codigo_promocion varchar(8),
    id_estatus int,
    empresa_rfc varchar(20),
    id_categoria int,
    imagen longblob,
    usos_disponibles int,
    FOREIGN KEY (id_tipo_promocion) REFERENCES tipo_promocion(id_tipo_promocion),
    FOREIGN KEY (id_estatus) REFERENCES estatus(id_estatus),
    FOREIGN KEY (empresa_rfc) REFERENCES empresa(rfc),
    FOREIGN KEY (id_categoria) REFERENCES categoria(id_categoria)
);

CREATE TABLE cupon (
    id_cupon int AUTO_INCREMENT PRIMARY KEY,
    codigo_cupon varchar(8),
    id_promocion int,
    fecha_generacion date,
    id_estatus int,
    FOREIGN KEY (id_promocion) REFERENCES promocion(id_promocion),
    FOREIGN KEY (id_estatus) REFERENCES estatus(id_estatus)
);

CREATE TABLE municipio (
    id_municipio int AUTO_INCREMENT PRIMARY KEY,
    nombre varchar(45),
    id_estado int,
    FOREIGN KEY (id_estado) REFERENCES estado(id_estado)
);

CREATE TABLE sucursal (
    id_sucursal int AUTO_INCREMENT PRIMARY KEY,
    nombre varchar(255),
    telefono varchar(20),
    latitud decimal(10,8),
    longitud decimal(11,8),
    nombre_encargado varchar(255),
    empresa_rfc varchar(20),
    FOREIGN KEY (empresa_rfc) REFERENCES empresa(rfc)
);

CREATE TABLE direccion (
    id_direccion int AUTO_INCREMENT PRIMARY KEY,
    calle varchar(255),
    numero int,
    codigo_postal varchar(10),
    colonia varchar(100),
    id_municipio int,
    id_cliente int,
    empresa_rfc varchar(20),
    id_sucursal int,
    FOREIGN KEY (id_municipio) REFERENCES municipio(id_municipio),
    FOREIGN KEY (id_cliente) REFERENCES cliente(id_cliente),
    FOREIGN KEY (empresa_rfc) REFERENCES empresa(rfc),
    FOREIGN KEY (id_sucursal) REFERENCES sucursal(id_sucursal)
);

-- Tabla compuesta sin la llave primaria idSucursalPromocion
CREATE TABLE sucursal_promocion (
    sucursal_id int,
    promocion_id int,
    FOREIGN KEY (sucursal_id) REFERENCES sucursal(id_sucursal),
    FOREIGN KEY (promocion_id) REFERENCES promocion(id_promocion),
    PRIMARY KEY (sucursal_id, promocion_id)
);


----------------------------------------------
-- Insertar estados
INSERT INTO estado (nombre) VALUES
('Aguascalientes'), ('Baja California'), ('Baja California Sur'), ('Campeche'), ('Chiapas'),
('Chihuahua'), ('Coahuila de Zaragoza'), ('Colima'), ('Durango'), ('Guanajuato');

-- Insertar municipios para los estados

-- Aguascalientes
INSERT INTO municipio (nombre, idEstado) VALUES
('Aguascalientes', 1), ('Asientos', 1), ('Calvillo', 1), ('Cosío', 1), ('Jesús María', 1),
('Pabellón de Arteaga', 1), ('Rincón de Romos', 1), ('San José de Gracia', 1),
('Tepezalá', 1), ('El Llano', 1);

-- Baja California
INSERT INTO municipio (nombre, idEstado) VALUES
('Tijuana', 2), ('Mexicali', 2), ('Ensenada', 2), ('Rosarito', 2), ('Tecate', 2),
('Playas de Rosarito', 2), ('La Rumorosa', 2), ('San Felipe', 2), ('Puertecitos', 2),
('San Quintín', 2);

-- Baja California Sur
INSERT INTO municipio (nombre, idEstado) VALUES
('La Paz', 3), ('Cabo San Lucas', 3), ('San José del Cabo', 3), ('Comondú', 3), ('Loreto', 3),
('Mulegé', 3), ('Santa Rosalía', 3), ('Guerrero Negro', 3), ('Villa Alberto Andrés Alvarado Arámburo', 3),
('Ciudad Constitución', 3);

-- Campeche
INSERT INTO municipio (nombre, idEstado) VALUES
('Campeche', 4), ('Calkiní', 4), ('Carmen', 4), ('Champotón', 4), ('Hecelchakán', 4),
('Hopelchén', 4), ('Palizada', 4), ('Tenabo', 4), ('Escárcega', 4), ('Calakmul', 4);

-- Chiapas
INSERT INTO municipio (nombre, idEstado) VALUES
('Tuxtla Gutiérrez', 5), ('Tapachula', 5), ('San Cristóbal de las Casas', 5),
('Tonalá', 5), ('Chiapa de Corzo', 5), ('Comitán de Domínguez', 5), ('Ocosingo', 5),
('Villaflores', 5), ('Palenque', 5), ('Cintalapa', 5);

-- Chihuahua
INSERT INTO municipio (nombre, idEstado) VALUES
('Chihuahua', 6), ('Juárez', 6), ('Cuauhtémoc', 6), ('Delicias', 6), ('Parral', 6),
('Hidalgo del Parral', 6), ('Nuevo Casas Grandes', 6), ('Camargo', 6), ('Jiménez', 6),
('Meoqui', 6);

-- Coahuila de Zaragoza
INSERT INTO municipio (nombre, idEstado) VALUES
('Saltillo', 7), ('Torreón', 7), ('Monclova', 7), ('Piedras Negras', 7), ('Acuña', 7),
('Matamoros', 7), ('Sabinas', 7), ('Nueva Rosita', 7), ('Frontera', 7), ('Allende', 7);

-- Colima
INSERT INTO municipio (nombre, idEstado) VALUES
('Colima', 8), ('Manzanillo', 8), ('Tecomán', 8), ('Villa de Álvarez', 8), ('Minatitlán', 8),
('Armería', 8), ('Cuauhtémoc', 8), ('Coquimatlán', 8), ('Comala', 8), ('Ixtlahuacán', 8);

-- Durango
INSERT INTO municipio (nombre, idEstado) VALUES
('Durango', 9), ('Gómez Palacio', 9), ('Lerdo', 9), ('Victoria de Durango', 9), ('Canatlán', 9),
('Tlahualilo', 9), ('Guadalupe Victoria', 9), ('San Juan del Río', 9), ('Peñón Blanco', 9),
('Pueblo Nuevo', 9);

-- Guanajuato
INSERT INTO municipio (nombre, idEstado) VALUES
('León', 10), ('Irapuato', 10), ('Celaya', 10), ('Salamanca', 10), ('Guanajuato', 10),
('San Miguel de Allende', 10), ('Acámbaro', 10), ('Silao', 10), ('Dolores Hidalgo', 10),
('Valle de Santiago', 10);

-- Insertar roles
INSERT INTO rol (nombreRol) VALUES ('Administrador general'), ('Administrador comercial');

-- Insertar estatus
INSERT INTO estatus (nombreEstatus) VALUES ('Activo'), ('Inactivo');

----------------------------------------------

-- SELECT de la tabla estado
SELECT * FROM estado;

-- SELECT de la tabla estatus
SELECT * FROM estatus;

-- SELECT de la tabla tipo_promocion
SELECT * FROM tipo_promocion;

-- SELECT de la tabla categoria
SELECT * FROM categoria;

-- SELECT de la tabla rol
SELECT * FROM rol;

-- SELECT de la tabla empresa
SELECT * FROM empresa;

-- SELECT de la tabla cliente
SELECT * FROM cliente;

-- SELECT de la tabla usuario
SELECT * FROM usuario;

-- SELECT de la tabla promocion
SELECT * FROM promocion;

-- SELECT de la tabla cupon
SELECT * FROM cupon;

-- SELECT de la tabla municipio
SELECT * FROM municipio;

-- SELECT de la tabla sucursal
SELECT * FROM sucursal;

-- SELECT de la tabla direccion
SELECT * FROM direccion;

-- SELECT de la tabla sucursal_promocion
SELECT * FROM sucursal_promocion;
